# Generated by Django 4.2.24 on 2025-09-09 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='e.g. about, contact', max_length=64)),
                ('label_en', models.CharField(max_length=255)),
                ('label_ar', models.CharField(blank=True, max_length=255, null=True)),
                ('route', models.CharField(max_length=255)),
                ('is_external', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=255)),
                ('title_ar', models.CharField(blank=True, max_length=255, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('description_ar', models.TextField(blank=True, null=True)),
                ('button_en', models.CharField(blank=True, max_length=255, null=True)),
                ('button_ar', models.CharField(blank=True, max_length=255, null=True)),
                ('background_image', models.CharField(blank=True, max_length=512, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_en', models.CharField(max_length=255)),
                ('label_ar', models.CharField(blank=True, max_length=255, null=True)),
                ('route', models.CharField(help_text='URL path or route name', max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=100)),
                ('name_ar', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.CharField(max_length=512)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
