# .github/workflows/ci.yml
name: CI & Code Quality Checks

on:
  push:
    branches-ignore: [main]
  pull_request:
    types: [opened, synchronize, reopened]

env:
  DJANGO_SETTINGS_MODULE: config.settings.dev
  DATABASE_URL: postgres://django:django@localhost:5432/django
  REDIS_URL: redis://localhost:6379/1
  SECRET_KEY: test-secret

jobs:
  test-lint:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: django
          POSTGRES_PASSWORD: django
          POSTGRES_DB: django
        ports: ['5432:5432']
        options: >-
          --health-cmd="pg_isready -U django"
          --health-interval=10s --health-timeout=5s --health-retries=5
      redis:
        image: redis:7
        ports: ['6379:6379']
        options: >-
          --health-cmd="redis-cli ping"
          --health-interval=10s --health-timeout=5s --health-retries=5
        
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }

      - name: Install dependencies
        run: pip install -r requirements/dev.txt

      - name: Run Pre-Commit Checks
        run: pre-commit run --all-files

      - name: Run Tests with Coverage
        run: pytest --cov=apps

  coderabbit:
    runs-on: ubuntu-latest
    needs: test-lint
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      
      - name: Install OpenAI/LLM client (Example)
        run: pip install openai

      - name: Generate Code Summary & Diagram
        # Assuming your script is at scripts/code_rabbit_summary.py
        run: python scripts/code_rabbit_summary.py > pr-summary.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Post PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: code-rabbit-summary
          path: pr-summary.md